package bill;

import reservation.Reservation;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manager class responsible for orchestrating the billing process.
 * Uses the Strategy Pattern via BillingStrategy to dynamically calculate 
 * the bill amount based on different rules (Daily, Hourly, etc.).
 */
public class BillManager {
    private BillingStrategy billingStrategy;

    // Thread-safe map to store all bills generated by this manager
    private final Map<Integer,Bill> bills = new ConcurrentHashMap<>();

    public BillManager(BillingStrategy billingStrategy){
        this.billingStrategy = billingStrategy;
    }

    public Bill generateBill(Reservation reservation){
        Bill bill = billingStrategy.generateBill(reservation);
        bills.put(bill.getBillId(),bill);
        return bill;
    }

    public Optional<Bill> getBill(int billId){
        return Optional.ofNullable(bills.get(billId));
    }

    public void setBillingStrategy(BillingStrategy billingStrategy){
        this.billingStrategy = billingStrategy;
    }
}
